version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      api-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      web-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
    groups:
      worker-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/worker"
    schedule:
      interval: "weekly"
