/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessingJobIdRouteImport } from './routes/processing.$jobId'
import { Route as DifficultyDeckIdRouteImport } from './routes/difficulty.$deckId'
import { Route as ExercisesDeckDeckIdClipClipIdRouteImport } from './routes/exercises.deck.$deckId.clip.$clipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingJobIdRoute = ProcessingJobIdRouteImport.update({
  id: '/processing/$jobId',
  path: '/processing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DifficultyDeckIdRoute = DifficultyDeckIdRouteImport.update({
  id: '/difficulty/$deckId',
  path: '/difficulty/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesDeckDeckIdClipClipIdRoute =
  ExercisesDeckDeckIdClipClipIdRouteImport.update({
    id: '/exercises/deck/$deckId/clip/$clipId',
    path: '/exercises/deck/$deckId/clip/$clipId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/difficulty/$deckId': typeof DifficultyDeckIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/exercises/deck/$deckId/clip/$clipId': typeof ExercisesDeckDeckIdClipClipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/difficulty/$deckId': typeof DifficultyDeckIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/exercises/deck/$deckId/clip/$clipId': typeof ExercisesDeckDeckIdClipClipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/difficulty/$deckId': typeof DifficultyDeckIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/exercises/deck/$deckId/clip/$clipId': typeof ExercisesDeckDeckIdClipClipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/difficulty/$deckId'
    | '/processing/$jobId'
    | '/exercises/deck/$deckId/clip/$clipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/difficulty/$deckId'
    | '/processing/$jobId'
    | '/exercises/deck/$deckId/clip/$clipId'
  id:
    | '__root__'
    | '/'
    | '/difficulty/$deckId'
    | '/processing/$jobId'
    | '/exercises/deck/$deckId/clip/$clipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DifficultyDeckIdRoute: typeof DifficultyDeckIdRoute
  ProcessingJobIdRoute: typeof ProcessingJobIdRoute
  ExercisesDeckDeckIdClipClipIdRoute: typeof ExercisesDeckDeckIdClipClipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$jobId': {
      id: '/processing/$jobId'
      path: '/processing/$jobId'
      fullPath: '/processing/$jobId'
      preLoaderRoute: typeof ProcessingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/difficulty/$deckId': {
      id: '/difficulty/$deckId'
      path: '/difficulty/$deckId'
      fullPath: '/difficulty/$deckId'
      preLoaderRoute: typeof DifficultyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/deck/$deckId/clip/$clipId': {
      id: '/exercises/deck/$deckId/clip/$clipId'
      path: '/exercises/deck/$deckId/clip/$clipId'
      fullPath: '/exercises/deck/$deckId/clip/$clipId'
      preLoaderRoute: typeof ExercisesDeckDeckIdClipClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DifficultyDeckIdRoute: DifficultyDeckIdRoute,
  ProcessingJobIdRoute: ProcessingJobIdRoute,
  ExercisesDeckDeckIdClipClipIdRoute: ExercisesDeckDeckIdClipClipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
